{% set name = "shyaml" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6f0f7d7dc85707a540bdec202eab59ae475cbcd1d582cde623799b1b21df1dc
  patches:
    # this is needed to make conda entry point work.
    - cli-args.patch

build:
  noarch: python
  number: 0
  script: |
    $PYTHON setup.py install
    cp shyaml "$SP_DIR/shyaml.py"
  entry_points:
    - shyaml = shyaml:main

requirements:
  host:
    - python
    - setuptools
    - d2to1
    - pyyaml
  run:
    - python
    - pyyaml

test:
  commands:
    shyaml --help

about:
  home: https://github.com/0k/shyaml
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'YAML for command line'

extra:
  recipe-maintainers:
    - scopatz
